# Generated by Django 3.2.8 on 2021-10-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SBN_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Following format: char(1 -> 20).', max_length=20, unique=True, verbose_name='product_category.')),
            ],
            options={
                'verbose_name': 'product_category.',
                'verbose_name_plural': 'product_categories.',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_uid', models.CharField(help_text='Following format: char(1 -> 32).', max_length=32, verbose_name='product_uid.')),
                ('name', models.CharField(help_text='Following format: char(1 -> 40).', max_length=40, verbose_name='product_name.')),
                ('description', models.TextField(help_text='Following format: char(1 -> 40).', verbose_name='product_description.')),
                ('price', models.DecimalField(decimal_places=15, help_text='Following format: dec(1 -> 30:15).', max_digits=30, verbose_name='product_price.')),
                ('discount', models.DecimalField(decimal_places=15, help_text='Following format: dec(1 -> 30:15).', max_digits=30, verbose_name='product_discount.')),
                ('graph', models.CharField(help_text='Following format: char(1 -> 1000).', max_length=1000, verbose_name='product_name.')),
                ('quantity', models.DecimalField(decimal_places=15, help_text='Following format: dec(1 -> 30:15).', max_digits=30, verbose_name='product_quantity.')),
                ('status', models.BooleanField(default=True, help_text='products still have?', verbose_name='product_status?')),
                ('category', models.ForeignKey(help_text='Following format: char(1 -> 38).', on_delete=django.db.models.deletion.CASCADE, to='SBN_Product.category', verbose_name='product_category.')),
                ('owner_uid', models.ForeignKey(help_text='Following format: char(1 -> 38).', on_delete=django.db.models.deletion.CASCADE, to='SBN_User.userinfo', verbose_name='owner_uid.')),
            ],
            options={
                'verbose_name': 'product.',
                'verbose_name_plural': 'products.',
            },
        ),
    ]
